### ISSUE TITLE
[BUG] Error after updating to Foundry v11 

### ISSUE THREAD

**Issue by TheBakaPenguin** [TooPick/gdoc-journals-foundry-vtt#6]
Hello! This module has been extremely useful and wonderful for the past several months. Unfortunately, my server has been updated to version 11 of Foundry and now I get the following error when trying to sync pages:

![Error log](https://github.com/TooPick/gdoc-journals-foundry-vtt/assets/148724238/9fa9f60d-83a3-4716-9af7-23b92098d4e3)

I don't know if this project is still in development as it's been 9 months since the last update, but it would really be a shame to see it go.

I hope all is well, and take care!

**Comment by TooPick** [comment]
Hi, I found the bug, I will make a new release soon. But I don't know how it could work before ^^
I don't have time and desire to make amelioration now, the module fulfills all my needs. Ideas of other users are cool, but it will need some dev to work, that's why there are no updates since 9 months.

Thank you for the feedback.
I'm glad you like the module.

**Comment by TooPick** [comment]
I've just released the new version, it should work now
